# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a8cedd7c0fe0938807798977485915e886c480ab2d37170a9c96ccf193735198c4050fe4a13ebecc6961bf8447b0585bf2c2106579e7f9b1934c817b958d42f4

test:
  secret_key_base: 28d7c0c78e6bdbd1bc1c49dd31780719069d7d08155f108c46b91dbfa5b37624a7f4c3ce6546ead59e85558bb8e266f2ad524ea64c250c413398d9cb175c78b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
